### ISSUE TITLE
Bug: @gmap-vue/v3/composables package throws an exception

### ISSUE THREAD

**Issue by hmalinie** [diegoazh/gmap-vue#329]
## Describe the bug

On a nuxt 3 project, importing `@gmap-vue/v3/composables` package throws an exception.

## To reproduce

https://codesandbox.io/p/devbox/hopeful-shape-vk4cj9?file=%2Fapp.vue%3A7%2C1

## Expected behavior

No exception.

## Current behavior

The exception :

```
[nuxt] [request error] [unhandled] [500] The requested module './keys.es.js' does not provide an export named '$circleShapePromise'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)  
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)  
  at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:383:28)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:253:24)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:189:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:233:12)  
  at async ./@gmap-vue/v3/composables:1:31  
  at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:362:5)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:346:5)
```

## Additional context

Dynamic frontend import is working correctly :

```
onMounted(async () => {
  const { useGoogleMapsApiPromiseLazy } = await import("@gmap-vue/v3/composables");
  const google = await useGoogleMapsApiPromiseLazy();
  console.log(google);
});
```

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [ ] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
Hello @hmalinie, I couldn't reproduce it. I used your sandbox, added the hook and imports, and all works as expected. If the issue still remains, please feel free to re-open this.
